apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaya-deploy-app-health
  labels:
    app: jaya-deploy-health
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jaya-deploy-health
  template:
    metadata:
      labels:
        app: jaya-deploy-health
    spec:
      containers:
      - name: jaya-deploy-container
        image: jaya002/web-server:latest
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: jaya-deploy-health-service
  labels:
    app: jaya-deploy-health
spec:
  selector:
    app: jaya-deploy-health

  type: NodePort
  ports:
  - nodePort: 31040 
    port: 8082
    targetPort: 8082
